name: Newton Summer Project CI Pipeline

on: [push]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: xcodebuild test -project IosSummerProject.xcodeproj -scheme IosSummerProjectTests -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.5,name=iPhone 11 Pro"
