name: Newton iOS Summer Project - CI Pipeline

on:
  pull_request:
    branches:
      - Development

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build & Test
      run: xcodebuild clean test -workspace IosSummerProject.xcworkspace -scheme IosSummerProject -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.6,name=iPhone 11 Pro" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
