name: Newton iOS Summer Project - CI Pipeline

on:
  pull_request:
    branches:
      - Development

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build & Test
      run: xcodebuild clean test -workspace IosSummerProject.xcworkspace -scheme IosSummerProject -sdk iphonesimulator -destination 'platform=iOS Simulator, id=3A1084C2-124C-4AB5-B6CD-F1BE6A1F4F28, OS=13.6, name=iPhone 11' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
